
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 * * * *'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install with Maven
      run: mvn -B install --file pom.xml
    - name: Run Checkstyle
      run: mvn checkstyle:check -B -f pom.xml
    - name: Run unit tests
      run: mvn test
    - name: Test Main class
      run: mvn exec:java -Dexec.mainClass="org.ekwateur.Main"


